on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload CSS Files to S3 with Correct MIME Type
        run: |
          # Upload CSS files with the correct MIME type
          aws s3 cp .stylesheet.css s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive --exclude "*" --include "*.css" --content-type "text/css"

      - name: Sync Website Files to S3 with Public Read Access
        run: |
          # Sync other files to S3, excluding CSS (already uploaded)
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --acl public-read --exclude "*.css"
